name: task execution
on: [push]
jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: Echo my name
        run: echo "My name is not Sunny"
      - name: Multiple command execution
        run:
          node -v
          echo "This is executing second time"
          echo $USER
          cat /etc/os-release
  run-windows-command:
    runs-on: windows-latest
    steps:
      - name: Dieplay current working directory
        run: Get-Location
      - name: Bash Shell execution
        run: pwd
        shell: Bash
